swagger: '2.0'
info:
  version: '1.0.0'
  title: 'Service Promotion Details'
  contact:
    name: Vinaykumar Irabatti
    email: Vinaykumar.Irabatti@T-Mobile.com

schemes:
 - http

consumes:
  - application/json

produces:
  - application/json

paths:
  /service-promo-details:
    get:
      summary: Get a list of service promotions
      description: Retrieve a list of service promotions
      parameters:
        - $ref: 'promotions_parameters.yaml#/ban'
      responses:
        200:
          description: Returns a list of service promotions.
          schema:
            $ref: 'promotions_definitions.yaml#/Promos'
        400:
          $ref: 'promotions_responses.yaml#/RequestErrorResponse'
        500:
          $ref: 'promotions_responses.yaml#/ServerErrorResponse'
        default:
          $ref: 'promotions_responses.yaml#/UnknownResponse'
